export const CONTEXT_LAYER_STORAGE_KEY = "grigori:context-layers";
export const OPERATIONAL_LAYER_STORAGE_KEY = "grigori:operational-layers";

export const DEFAULT_LAYER_DENSITY = {
  contextPorts: "low",
  contextCities: "low",
  contextMilitaryBases: "low",
  satellites: "low",
  flights: "low",
  vessels: "low",
};

export const LAYER_DENSITY_CAPS = {
  contextPorts: { low: 40, medium: 90, high: 160 },
  contextCities: { low: 35, medium: 90, high: 180 },
  contextMilitaryBases: { low: 18, medium: 45, high: 90 },
  satellites: { low: 70, medium: 160, high: 320 },
  flights: { low: 40, medium: 90, high: 160 },
  vessels: { low: 35, medium: 80, high: 150 },
};

export const CONTEXT_LAYER_DEFS = {
  contextChokepoints: {
    label: "Chokepoints",
    type: "chokepoint",
    icon: "C",
    color: "#f7b84b",
    desc: "Strategic maritime chokepoints",
  },
  contextPorts: {
    label: "Ports",
    type: "port",
    icon: "P",
    color: "#69e7ff",
    desc: "Major port and logistics nodes",
  },
  contextAirports: {
    label: "Airports",
    type: "airport",
    icon: "A",
    color: "#9bd6ff",
    desc: "Strategic aviation nodes",
  },
  contextEnergy: {
    label: "Energy",
    type: "energy",
    icon: "E",
    color: "#6ee7b7",
    desc: "Energy infrastructure context",
  },
  contextCities: {
    label: "Cities",
    type: "city",
    icon: "C",
    color: "#8aa7c7",
    desc: "Major city orientation layer",
  },
  contextMilitaryBases: {
    label: "Public Bases",
    type: "military_base",
    icon: "B",
    color: "#b7c7d8",
    desc: "Publicly known military facilities",
  },
};

export const CONTEXT_LAYER_ITEMS = [
  {
    id: "ctx-hormuz",
    name: "Strait of Hormuz",
    type: "chokepoint",
    region: "Persian Gulf / Gulf of Oman",
    coordinates: [26.6, 56.3],
    geoAccuracy: "region",
    whyItMatters: "Critical oil and LNG transit chokepoint linking Gulf producers to global shipping routes.",
    tags: ["oil", "shipping", "iran", "gulf"],
  },
  {
    id: "ctx-bab-el-mandeb",
    name: "Bab el-Mandeb",
    type: "chokepoint",
    region: "Red Sea / Gulf of Aden",
    coordinates: [12.6, 43.3],
    geoAccuracy: "region",
    whyItMatters: "Narrow maritime passage connecting the Red Sea to the Gulf of Aden and Suez-bound traffic.",
    tags: ["shipping", "red sea", "suez", "yemen"],
  },
  {
    id: "ctx-suez",
    name: "Suez Canal",
    type: "chokepoint",
    region: "Egypt",
    coordinates: [30.6, 32.3],
    geoAccuracy: "region",
    whyItMatters: "Major Europe-Asia shipping corridor; disruption can reroute vessels around the Cape of Good Hope.",
    tags: ["shipping", "trade", "egypt"],
  },
  {
    id: "ctx-bosporus",
    name: "Bosporus",
    type: "chokepoint",
    region: "Turkey / Black Sea",
    coordinates: [41.12, 29.06],
    geoAccuracy: "region",
    whyItMatters: "Gateway between the Black Sea and Mediterranean for naval, grain, and energy-linked traffic.",
    tags: ["black sea", "shipping", "turkey"],
  },
  {
    id: "ctx-taiwan-strait",
    name: "Taiwan Strait",
    type: "chokepoint",
    region: "Taiwan / China",
    coordinates: [24.5, 120.8],
    geoAccuracy: "region",
    whyItMatters: "Strategic maritime and air corridor near critical semiconductor supply chains.",
    tags: ["taiwan", "semiconductors", "shipping"],
  },
  {
    id: "ctx-malacca",
    name: "Strait of Malacca",
    type: "chokepoint",
    region: "Malaysia / Singapore / Indonesia",
    coordinates: [2.6, 101.0],
    geoAccuracy: "region",
    whyItMatters: "One of the world's busiest energy and container shipping corridors.",
    tags: ["shipping", "energy", "asia"],
  },
  {
    id: "ctx-panama",
    name: "Panama Canal",
    type: "chokepoint",
    region: "Panama",
    coordinates: [9.08, -79.68],
    geoAccuracy: "region",
    whyItMatters: "Key Atlantic-Pacific transit corridor sensitive to drought, congestion, and trade disruption.",
    tags: ["shipping", "trade"],
  },
  {
    id: "ctx-gibraltar",
    name: "Strait of Gibraltar",
    type: "chokepoint",
    region: "Western Mediterranean",
    coordinates: [35.98, -5.6],
    geoAccuracy: "region",
    whyItMatters: "Mediterranean access point for Atlantic shipping, naval movement, and energy routes.",
    tags: ["shipping", "mediterranean"],
  },
  {
    id: "ctx-port-rotterdam",
    name: "Port of Rotterdam",
    type: "port",
    region: "Netherlands",
    coordinates: [51.95, 4.14],
    geoAccuracy: "city",
    whyItMatters: "Major European energy, container, and industrial logistics hub.",
    tags: ["port", "europe", "energy"],
  },
  {
    id: "ctx-port-singapore",
    name: "Port of Singapore",
    type: "port",
    region: "Singapore",
    coordinates: [1.26, 103.82],
    geoAccuracy: "city",
    whyItMatters: "Critical transshipment and bunkering hub near the Malacca-South China Sea corridor.",
    tags: ["port", "shipping", "asia"],
  },
  {
    id: "ctx-port-fujairah",
    name: "Fujairah",
    type: "port",
    region: "United Arab Emirates",
    coordinates: [25.12, 56.36],
    geoAccuracy: "city",
    whyItMatters: "Strategic oil storage and bunkering node outside the Strait of Hormuz.",
    tags: ["port", "oil", "hormuz"],
  },
  {
    id: "ctx-port-constanta",
    name: "Constanta",
    type: "port",
    region: "Romania / Black Sea",
    coordinates: [44.16, 28.65],
    geoAccuracy: "city",
    whyItMatters: "Black Sea port relevant to grain, NATO logistics, and regional shipping disruption.",
    tags: ["port", "black sea", "grain"],
  },
  {
    id: "ctx-airport-dxb",
    name: "Dubai International",
    type: "airport",
    region: "United Arab Emirates",
    coordinates: [25.25, 55.36],
    geoAccuracy: "city",
    whyItMatters: "Major global aviation hub near Gulf escalation and energy chokepoint risks.",
    tags: ["airport", "gulf", "logistics"],
  },
  {
    id: "ctx-airport-istanbul",
    name: "Istanbul Airport",
    type: "airport",
    region: "Turkey",
    coordinates: [41.26, 28.74],
    geoAccuracy: "city",
    whyItMatters: "Major aviation hub near Bosporus and Black Sea-related transit corridors.",
    tags: ["airport", "black sea", "turkey"],
  },
  {
    id: "ctx-airport-ben-gurion",
    name: "Ben Gurion Airport",
    type: "airport",
    region: "Israel",
    coordinates: [32.0, 34.89],
    geoAccuracy: "city",
    whyItMatters: "Regional aviation node sensitive to Middle East escalation and airspace disruption.",
    tags: ["airport", "middle east"],
  },
  {
    id: "ctx-energy-kharg",
    name: "Kharg Island",
    type: "energy",
    region: "Iran / Persian Gulf",
    coordinates: [29.24, 50.31],
    geoAccuracy: "region",
    whyItMatters: "Iranian oil export node relevant to Gulf and Hormuz risk monitoring.",
    tags: ["oil", "iran", "hormuz"],
  },
  {
    id: "ctx-energy-abqaiq",
    name: "Abqaiq",
    type: "energy",
    region: "Saudi Arabia",
    coordinates: [25.94, 49.67],
    geoAccuracy: "city",
    whyItMatters: "Major Saudi oil processing infrastructure with strategic energy-market relevance.",
    tags: ["oil", "saudi", "energy"],
  },
  {
    id: "ctx-energy-ras-tanura",
    name: "Ras Tanura",
    type: "energy",
    region: "Saudi Arabia / Persian Gulf",
    coordinates: [26.65, 50.16],
    geoAccuracy: "region",
    whyItMatters: "Major oil terminal and refinery area near Gulf maritime security dynamics.",
    tags: ["oil", "terminal", "gulf"],
  },
  {
    id: "ctx-energy-sumed",
    name: "Suez / SUMED Energy Corridor",
    type: "energy",
    region: "Egypt",
    coordinates: [29.95, 32.55],
    geoAccuracy: "region",
    whyItMatters: "Energy transit context connecting Red Sea, Suez, and Mediterranean flows.",
    tags: ["oil", "suez", "pipeline"],
  },
  {
    id: "ctx-port-shanghai",
    name: "Shanghai",
    type: "port",
    category: "container port",
    region: "East China Sea / Yangtze Delta",
    country: "China",
    coordinates: [31.23, 121.49],
    geoAccuracy: "city",
    importance: 98,
    whyItMatters: "One of the world's largest container gateways and a core China trade node.",
    tags: ["port", "china", "containers", "trade"],
  },
  {
    id: "ctx-port-antwerp-bruges",
    name: "Antwerp-Bruges",
    type: "port",
    category: "container and energy port",
    region: "North Sea / Western Europe",
    country: "Belgium",
    coordinates: [51.26, 4.38],
    geoAccuracy: "city",
    importance: 86,
    whyItMatters: "Major European container, chemical, and energy logistics hub.",
    tags: ["port", "europe", "containers", "energy"],
  },
  {
    id: "ctx-port-hamburg",
    name: "Hamburg",
    type: "port",
    category: "container port",
    region: "North Sea / Baltic access",
    country: "Germany",
    coordinates: [53.54, 9.97],
    geoAccuracy: "city",
    importance: 82,
    whyItMatters: "Strategic German logistics node connected to Central and Eastern European trade flows.",
    tags: ["port", "germany", "containers", "trade"],
  },
  {
    id: "ctx-port-la-long-beach",
    name: "Los Angeles / Long Beach",
    type: "port",
    category: "container port complex",
    region: "US West Coast",
    country: "United States",
    coordinates: [33.75, -118.22],
    geoAccuracy: "city",
    importance: 90,
    whyItMatters: "Largest US container gateway and a key trans-Pacific supply-chain node.",
    tags: ["port", "us", "pacific", "supply chains"],
  },
  {
    id: "ctx-port-ny-nj",
    name: "New York / New Jersey",
    type: "port",
    category: "container port complex",
    region: "US East Coast",
    country: "United States",
    coordinates: [40.67, -74.05],
    geoAccuracy: "city",
    importance: 84,
    whyItMatters: "Major Atlantic gateway for US consumer, industrial, and energy-linked cargo flows.",
    tags: ["port", "us", "atlantic", "containers"],
  },
  {
    id: "ctx-port-houston",
    name: "Houston",
    type: "port",
    category: "energy and industrial port",
    region: "US Gulf Coast",
    country: "United States",
    coordinates: [29.73, -95.27],
    geoAccuracy: "city",
    importance: 88,
    whyItMatters: "Critical Gulf Coast energy, petrochemical, and industrial shipping hub.",
    tags: ["port", "us", "energy", "gulf"],
  },
  {
    id: "ctx-port-jebel-ali",
    name: "Jebel Ali",
    type: "port",
    category: "container and logistics port",
    region: "Persian Gulf",
    country: "United Arab Emirates",
    coordinates: [25.01, 55.06],
    geoAccuracy: "city",
    importance: 90,
    whyItMatters: "Major Gulf logistics hub near Hormuz-linked shipping and energy routes.",
    tags: ["port", "gulf", "hormuz", "containers"],
  },
  {
    id: "ctx-port-busan",
    name: "Busan",
    type: "port",
    category: "container port",
    region: "Northeast Asia",
    country: "South Korea",
    coordinates: [35.1, 129.04],
    geoAccuracy: "city",
    importance: 88,
    whyItMatters: "Major Northeast Asian transshipment and industrial export node.",
    tags: ["port", "korea", "containers", "asia"],
  },
  {
    id: "ctx-port-ningbo-zhoushan",
    name: "Ningbo-Zhoushan",
    type: "port",
    category: "container and bulk port",
    region: "East China Sea",
    country: "China",
    coordinates: [29.87, 121.55],
    geoAccuracy: "city",
    importance: 94,
    whyItMatters: "One of China's largest cargo gateways for containers, energy, and bulk commodities.",
    tags: ["port", "china", "containers", "bulk"],
  },
  {
    id: "ctx-port-shenzhen",
    name: "Shenzhen",
    type: "port",
    category: "container port",
    region: "Pearl River Delta",
    country: "China",
    coordinates: [22.54, 114.05],
    geoAccuracy: "city",
    importance: 92,
    whyItMatters: "Core Pearl River Delta container gateway near major technology supply chains.",
    tags: ["port", "china", "technology", "containers"],
  },
  {
    id: "ctx-port-guangzhou",
    name: "Guangzhou",
    type: "port",
    category: "container and river port",
    region: "Pearl River Delta",
    country: "China",
    coordinates: [23.1, 113.26],
    geoAccuracy: "city",
    importance: 84,
    whyItMatters: "Major South China manufacturing and inland logistics gateway.",
    tags: ["port", "china", "manufacturing", "trade"],
  },
  {
    id: "ctx-port-hong-kong",
    name: "Hong Kong",
    type: "port",
    category: "container and finance-linked port",
    region: "South China Sea",
    country: "Hong Kong / China",
    coordinates: [22.3, 114.17],
    geoAccuracy: "city",
    importance: 80,
    whyItMatters: "Strategic commercial and financial gateway in the South China Sea trade system.",
    tags: ["port", "china", "finance", "trade"],
  },
  {
    id: "ctx-port-qingdao",
    name: "Qingdao",
    type: "port",
    category: "container and bulk port",
    region: "Yellow Sea",
    country: "China",
    coordinates: [36.07, 120.38],
    geoAccuracy: "city",
    importance: 84,
    whyItMatters: "Major northern China port with industrial, naval, and trade relevance.",
    tags: ["port", "china", "yellow sea", "industry"],
  },
  {
    id: "ctx-port-tianjin",
    name: "Tianjin",
    type: "port",
    category: "container and industrial port",
    region: "Bohai Gulf",
    country: "China",
    coordinates: [39.0, 117.72],
    geoAccuracy: "city",
    importance: 84,
    whyItMatters: "Primary maritime gateway for Beijing-Tianjin-Hebei industrial flows.",
    tags: ["port", "china", "bohai", "industry"],
  },
  {
    id: "ctx-port-klang",
    name: "Port Klang",
    type: "port",
    category: "container port",
    region: "Strait of Malacca",
    country: "Malaysia",
    coordinates: [3.0, 101.39],
    geoAccuracy: "city",
    importance: 82,
    whyItMatters: "Major Malacca-linked transshipment and Malaysian trade gateway.",
    tags: ["port", "malacca", "malaysia", "containers"],
  },
  {
    id: "ctx-port-tanjung-pelepas",
    name: "Tanjung Pelepas",
    type: "port",
    category: "container port",
    region: "Strait of Malacca",
    country: "Malaysia",
    coordinates: [1.36, 103.55],
    geoAccuracy: "city",
    importance: 80,
    whyItMatters: "Transshipment hub near Singapore and the Malacca chokepoint.",
    tags: ["port", "malacca", "transshipment"],
  },
  {
    id: "ctx-port-colombo",
    name: "Colombo",
    type: "port",
    category: "transshipment port",
    region: "Indian Ocean",
    country: "Sri Lanka",
    coordinates: [6.94, 79.84],
    geoAccuracy: "city",
    importance: 78,
    whyItMatters: "Indian Ocean transshipment node along Asia-Europe maritime routes.",
    tags: ["port", "indian ocean", "shipping"],
  },
  {
    id: "ctx-port-piraeus",
    name: "Piraeus",
    type: "port",
    category: "container and ferry port",
    region: "Eastern Mediterranean",
    country: "Greece",
    coordinates: [37.94, 23.64],
    geoAccuracy: "city",
    importance: 76,
    whyItMatters: "Eastern Mediterranean logistics node connecting Europe, Suez traffic, and Balkan routes.",
    tags: ["port", "mediterranean", "europe"],
  },
  {
    id: "ctx-port-ambarli",
    name: "Istanbul / Ambarli",
    type: "port",
    category: "container port",
    region: "Bosporus / Sea of Marmara",
    country: "Turkey",
    coordinates: [40.97, 28.69],
    geoAccuracy: "city",
    importance: 78,
    whyItMatters: "Strategic Turkish port near Bosporus and Black Sea access routes.",
    tags: ["port", "bosporus", "black sea", "turkey"],
  },
  {
    id: "ctx-port-odesa",
    name: "Odessa / Odesa",
    type: "port",
    category: "commercial port",
    region: "Black Sea",
    country: "Ukraine",
    coordinates: [46.48, 30.73],
    geoAccuracy: "city",
    importance: 82,
    whyItMatters: "Black Sea export node central to grain, infrastructure, and Ukraine-Russia maritime risk.",
    tags: ["port", "black sea", "ukraine", "grain"],
  },
  {
    id: "ctx-port-novorossiysk",
    name: "Novorossiysk",
    type: "port",
    category: "commercial and energy port",
    region: "Black Sea",
    country: "Russia",
    coordinates: [44.72, 37.77],
    geoAccuracy: "city",
    importance: 82,
    whyItMatters: "Major Russian Black Sea port with energy, grain, and maritime security relevance.",
    tags: ["port", "black sea", "russia", "energy"],
  },
  {
    id: "ctx-port-port-said",
    name: "Suez / Port Said",
    type: "port",
    category: "canal port",
    region: "Suez Canal",
    country: "Egypt",
    coordinates: [31.25, 32.3],
    geoAccuracy: "city",
    importance: 84,
    whyItMatters: "Northern Suez gateway for Asia-Europe shipping flows.",
    tags: ["port", "suez", "shipping"],
  },
  {
    id: "ctx-port-djibouti",
    name: "Djibouti",
    type: "port",
    category: "container and strategic port",
    region: "Bab el-Mandeb / Horn of Africa",
    country: "Djibouti",
    coordinates: [11.6, 43.15],
    geoAccuracy: "city",
    importance: 82,
    whyItMatters: "Strategic Red Sea logistics node near Bab el-Mandeb and regional military facilities.",
    tags: ["port", "red sea", "horn of africa", "shipping"],
  },
  {
    id: "ctx-port-durban",
    name: "Durban",
    type: "port",
    category: "container and bulk port",
    region: "Southern Africa",
    country: "South Africa",
    coordinates: [-29.88, 31.05],
    geoAccuracy: "city",
    importance: 72,
    whyItMatters: "Major Southern African trade gateway and Indian Ocean logistics node.",
    tags: ["port", "africa", "indian ocean"],
  },
  {
    id: "ctx-port-santos",
    name: "Santos",
    type: "port",
    category: "container and commodity port",
    region: "South Atlantic",
    country: "Brazil",
    coordinates: [-23.95, -46.33],
    geoAccuracy: "city",
    importance: 76,
    whyItMatters: "Brazil's major export gateway for commodities and containerized trade.",
    tags: ["port", "brazil", "commodities"],
  },
  {
    id: "ctx-port-panama-balboa-colon",
    name: "Panama / Balboa / Colon",
    type: "port",
    category: "canal port complex",
    region: "Panama Canal",
    country: "Panama",
    coordinates: [9.12, -79.75],
    geoAccuracy: "region",
    importance: 84,
    whyItMatters: "Atlantic-Pacific canal port complex central to hemispheric trade flows.",
    tags: ["port", "panama", "canal", "shipping"],
  },
  {
    id: "ctx-city-washington",
    name: "Washington, DC",
    type: "city",
    category: "capital",
    region: "North America",
    country: "United States",
    coordinates: [38.9, -77.04],
    geoAccuracy: "city",
    importance: 88,
    whyItMatters: "US federal decision center for sanctions, defense posture, and diplomacy.",
    tags: ["capital", "policy", "us"],
  },
  {
    id: "ctx-city-brussels",
    name: "Brussels",
    type: "city",
    category: "capital / institution hub",
    region: "Western Europe",
    country: "Belgium",
    coordinates: [50.85, 4.35],
    geoAccuracy: "city",
    importance: 86,
    whyItMatters: "EU and NATO institutional hub for sanctions, defense, and regulatory pressure.",
    tags: ["capital", "eu", "nato"],
  },
  {
    id: "ctx-city-london",
    name: "London",
    type: "city",
    category: "capital / financial hub",
    region: "Western Europe",
    country: "United Kingdom",
    coordinates: [51.51, -0.13],
    geoAccuracy: "city",
    importance: 84,
    whyItMatters: "Major policy, financial, insurance, and sanctions-linked decision center.",
    tags: ["capital", "finance", "insurance"],
  },
  {
    id: "ctx-city-berlin",
    name: "Berlin",
    type: "city",
    category: "capital",
    region: "Central Europe",
    country: "Germany",
    coordinates: [52.52, 13.4],
    geoAccuracy: "city",
    importance: 80,
    whyItMatters: "German policy center for EU, NATO, energy, and sanctions decisions.",
    tags: ["capital", "europe", "policy"],
  },
  {
    id: "ctx-city-paris",
    name: "Paris",
    type: "city",
    category: "capital",
    region: "Western Europe",
    country: "France",
    coordinates: [48.86, 2.35],
    geoAccuracy: "city",
    importance: 80,
    whyItMatters: "French diplomatic, defense, and EU policy center.",
    tags: ["capital", "europe", "policy"],
  },
  {
    id: "ctx-city-kyiv",
    name: "Kyiv",
    type: "city",
    category: "capital",
    region: "Eastern Europe",
    country: "Ukraine",
    coordinates: [50.45, 30.52],
    geoAccuracy: "city",
    importance: 86,
    whyItMatters: "Ukrainian decision center for war, infrastructure, and Black Sea risk.",
    tags: ["capital", "ukraine", "black sea"],
  },
  {
    id: "ctx-city-moscow",
    name: "Moscow",
    type: "city",
    category: "capital",
    region: "Eastern Europe / Russia",
    country: "Russia",
    coordinates: [55.76, 37.62],
    geoAccuracy: "city",
    importance: 86,
    whyItMatters: "Russian political and military decision center.",
    tags: ["capital", "russia", "policy"],
  },
  {
    id: "ctx-city-istanbul",
    name: "Istanbul",
    type: "city",
    category: "logistics hub",
    region: "Bosporus / Black Sea",
    country: "Turkey",
    coordinates: [41.01, 28.97],
    geoAccuracy: "city",
    importance: 82,
    whyItMatters: "Urban and logistics hub around Bosporus access between the Black Sea and Mediterranean.",
    tags: ["city", "bosporus", "shipping"],
  },
  {
    id: "ctx-city-ankara",
    name: "Ankara",
    type: "city",
    category: "capital",
    region: "Turkey",
    country: "Turkey",
    coordinates: [39.93, 32.86],
    geoAccuracy: "city",
    importance: 76,
    whyItMatters: "Turkish state decision center for NATO, Black Sea, and Middle East policy.",
    tags: ["capital", "turkey", "nato"],
  },
  {
    id: "ctx-city-dubai",
    name: "Dubai",
    type: "city",
    category: "financial / logistics hub",
    region: "Persian Gulf",
    country: "United Arab Emirates",
    coordinates: [25.2, 55.27],
    geoAccuracy: "city",
    importance: 82,
    whyItMatters: "Gulf logistics, finance, aviation, and energy-adjacent hub near Hormuz risk.",
    tags: ["city", "gulf", "logistics"],
  },
  {
    id: "ctx-city-doha",
    name: "Doha",
    type: "city",
    category: "capital / energy hub",
    region: "Persian Gulf",
    country: "Qatar",
    coordinates: [25.29, 51.53],
    geoAccuracy: "city",
    importance: 78,
    whyItMatters: "Qatari LNG and diplomatic center near Gulf escalation dynamics.",
    tags: ["capital", "lng", "gulf"],
  },
  {
    id: "ctx-city-riyadh",
    name: "Riyadh",
    type: "city",
    category: "capital",
    region: "Arabian Peninsula",
    country: "Saudi Arabia",
    coordinates: [24.71, 46.68],
    geoAccuracy: "city",
    importance: 82,
    whyItMatters: "Saudi decision center for energy, security, and regional diplomacy.",
    tags: ["capital", "oil", "gulf"],
  },
  {
    id: "ctx-city-tehran",
    name: "Tehran",
    type: "city",
    category: "capital",
    region: "Iran",
    country: "Iran",
    coordinates: [35.69, 51.39],
    geoAccuracy: "city",
    importance: 84,
    whyItMatters: "Iranian political decision center for Gulf, nuclear, sanctions, and regional posture.",
    tags: ["capital", "iran", "hormuz"],
  },
  {
    id: "ctx-city-tel-aviv",
    name: "Tel Aviv",
    type: "city",
    category: "technology / financial hub",
    region: "Eastern Mediterranean",
    country: "Israel",
    coordinates: [32.08, 34.78],
    geoAccuracy: "city",
    importance: 78,
    whyItMatters: "Regional technology, finance, and security-adjacent urban hub.",
    tags: ["city", "technology", "middle east"],
  },
  {
    id: "ctx-city-taipei",
    name: "Taipei",
    type: "city",
    category: "capital / technology hub",
    region: "Taiwan Strait",
    country: "Taiwan",
    coordinates: [25.03, 121.56],
    geoAccuracy: "city",
    importance: 86,
    whyItMatters: "Taiwan political and semiconductor-adjacent decision center.",
    tags: ["capital", "taiwan", "semiconductors"],
  },
  {
    id: "ctx-city-beijing",
    name: "Beijing",
    type: "city",
    category: "capital",
    region: "China",
    country: "China",
    coordinates: [39.9, 116.41],
    geoAccuracy: "city",
    importance: 88,
    whyItMatters: "Chinese political decision center for trade, Taiwan, technology, and security policy.",
    tags: ["capital", "china", "policy"],
  },
  {
    id: "ctx-city-shanghai",
    name: "Shanghai",
    type: "city",
    category: "financial / logistics hub",
    region: "East China",
    country: "China",
    coordinates: [31.23, 121.47],
    geoAccuracy: "city",
    importance: 84,
    whyItMatters: "Financial and logistics hub connected to China trade and supply-chain risk.",
    tags: ["city", "finance", "port"],
  },
  {
    id: "ctx-city-singapore",
    name: "Singapore",
    type: "city",
    category: "financial / logistics hub",
    region: "Malacca / Southeast Asia",
    country: "Singapore",
    coordinates: [1.35, 103.82],
    geoAccuracy: "city",
    importance: 86,
    whyItMatters: "Financial, maritime, and logistics hub near Malacca and South China Sea routes.",
    tags: ["city", "shipping", "finance"],
  },
  {
    id: "ctx-city-new-delhi",
    name: "New Delhi",
    type: "city",
    category: "capital",
    region: "South Asia",
    country: "India",
    coordinates: [28.61, 77.21],
    geoAccuracy: "city",
    importance: 78,
    whyItMatters: "Indian policy center for Indo-Pacific, energy, and trade alignment.",
    tags: ["capital", "india", "policy"],
  },
  {
    id: "ctx-base-ramstein",
    name: "Ramstein Air Base",
    type: "military_base",
    category: "air base",
    region: "Western Europe",
    country: "Germany",
    coordinates: [49.44, 7.6],
    geoAccuracy: "city",
    importance: 82,
    whyItMatters: "Publicly known NATO/US air and logistics facility supporting European theater operations.",
    riskNotes: "Public contextual reference only; no tactical readiness implied.",
    tags: ["public base", "nato", "air"],
  },
  {
    id: "ctx-base-incirlik",
    name: "Incirlik Air Base",
    type: "military_base",
    category: "air base",
    region: "Turkey / Eastern Mediterranean",
    country: "Turkey",
    coordinates: [37.0, 35.43],
    geoAccuracy: "city",
    importance: 80,
    whyItMatters: "Publicly known air facility relevant to NATO, Middle East, and Eastern Mediterranean context.",
    riskNotes: "Public contextual reference only; no tactical readiness implied.",
    tags: ["public base", "nato", "air"],
  },
  {
    id: "ctx-base-al-udeid",
    name: "Al Udeid Air Base",
    type: "military_base",
    category: "air base",
    region: "Persian Gulf",
    country: "Qatar",
    coordinates: [25.12, 51.31],
    geoAccuracy: "city",
    importance: 84,
    whyItMatters: "Publicly known regional air facility near Gulf and Hormuz-linked security dynamics.",
    riskNotes: "Public contextual reference only; no tactical readiness implied.",
    tags: ["public base", "gulf", "air"],
  },
  {
    id: "ctx-base-diego-garcia",
    name: "Diego Garcia",
    type: "military_base",
    category: "naval / air facility",
    region: "Indian Ocean",
    country: "British Indian Ocean Territory",
    coordinates: [-7.31, 72.41],
    geoAccuracy: "region",
    importance: 82,
    whyItMatters: "Publicly known Indian Ocean facility relevant to long-range logistics and maritime context.",
    riskNotes: "Public contextual reference only; no tactical readiness implied.",
    tags: ["public base", "indian ocean", "naval"],
  },
  {
    id: "ctx-base-rota",
    name: "Rota Naval Base",
    type: "military_base",
    category: "naval base",
    region: "Western Mediterranean / Atlantic",
    country: "Spain",
    coordinates: [36.65, -6.35],
    geoAccuracy: "city",
    importance: 76,
    whyItMatters: "Publicly known naval facility near Atlantic-Mediterranean access routes.",
    riskNotes: "Public contextual reference only; no tactical readiness implied.",
    tags: ["public base", "naval", "mediterranean"],
  },
  {
    id: "ctx-base-souda-bay",
    name: "Souda Bay",
    type: "military_base",
    category: "naval / air facility",
    region: "Eastern Mediterranean",
    country: "Greece",
    coordinates: [35.49, 24.15],
    geoAccuracy: "city",
    importance: 78,
    whyItMatters: "Publicly known facility relevant to Eastern Mediterranean maritime and air context.",
    riskNotes: "Public contextual reference only; no tactical readiness implied.",
    tags: ["public base", "mediterranean", "naval"],
  },
  {
    id: "ctx-base-camp-humphreys",
    name: "Camp Humphreys",
    type: "military_base",
    category: "army installation",
    region: "Korean Peninsula",
    country: "South Korea",
    coordinates: [36.96, 127.03],
    geoAccuracy: "city",
    importance: 78,
    whyItMatters: "Publicly known facility relevant to Korean Peninsula security context.",
    riskNotes: "Public contextual reference only; no tactical readiness implied.",
    tags: ["public base", "korea", "army"],
  },
  {
    id: "ctx-base-yokosuka",
    name: "Yokosuka Naval Base",
    type: "military_base",
    category: "naval base",
    region: "Western Pacific",
    country: "Japan",
    coordinates: [35.29, 139.66],
    geoAccuracy: "city",
    importance: 82,
    whyItMatters: "Publicly known naval facility relevant to Indo-Pacific and Taiwan Strait context.",
    riskNotes: "Public contextual reference only; no tactical readiness implied.",
    tags: ["public base", "naval", "indo-pacific"],
  },
  {
    id: "ctx-base-kadena",
    name: "Kadena Air Base",
    type: "military_base",
    category: "air base",
    region: "Western Pacific",
    country: "Japan",
    coordinates: [26.35, 127.77],
    geoAccuracy: "city",
    importance: 82,
    whyItMatters: "Publicly known air facility near East China Sea and Taiwan Strait contingency areas.",
    riskNotes: "Public contextual reference only; no tactical readiness implied.",
    tags: ["public base", "air", "indo-pacific"],
  },
  {
    id: "ctx-base-bahrain",
    name: "Naval Support Activity Bahrain",
    type: "military_base",
    category: "naval facility",
    region: "Persian Gulf",
    country: "Bahrain",
    coordinates: [26.21, 50.61],
    geoAccuracy: "city",
    importance: 82,
    whyItMatters: "Publicly known naval facility relevant to Gulf maritime security and Hormuz context.",
    riskNotes: "Public contextual reference only; no tactical readiness implied.",
    tags: ["public base", "naval", "hormuz"],
  },
  {
    id: "ctx-base-norfolk",
    name: "Naval Station Norfolk",
    type: "military_base",
    category: "naval base",
    region: "US East Coast",
    country: "United States",
    coordinates: [36.95, -76.33],
    geoAccuracy: "city",
    importance: 76,
    whyItMatters: "Publicly known major naval facility relevant to Atlantic maritime posture.",
    riskNotes: "Public contextual reference only; no tactical readiness implied.",
    tags: ["public base", "naval", "atlantic"],
  },
  {
    id: "ctx-base-fort-liberty",
    name: "Fort Liberty / Bragg",
    type: "military_base",
    category: "army installation",
    region: "US East Coast",
    country: "United States",
    coordinates: [35.14, -79.0],
    geoAccuracy: "city",
    importance: 72,
    whyItMatters: "Publicly known US Army installation included for broad strategic context only.",
    riskNotes: "Public contextual reference only; no tactical readiness implied.",
    tags: ["public base", "army", "us"],
  },
  {
    id: "ctx-base-pearl-harbor",
    name: "Pearl Harbor",
    type: "military_base",
    category: "naval base",
    region: "Central Pacific",
    country: "United States",
    coordinates: [21.36, -157.95],
    geoAccuracy: "city",
    importance: 78,
    whyItMatters: "Publicly known Pacific naval facility relevant to Indo-Pacific logistics and posture.",
    riskNotes: "Public contextual reference only; no tactical readiness implied.",
    tags: ["public base", "naval", "pacific"],
  },
  {
    id: "ctx-base-sigonella",
    name: "Sigonella",
    type: "military_base",
    category: "air station",
    region: "Central Mediterranean",
    country: "Italy",
    coordinates: [37.4, 14.92],
    geoAccuracy: "city",
    importance: 74,
    whyItMatters: "Publicly known air facility relevant to Mediterranean surveillance and logistics context.",
    riskNotes: "Public contextual reference only; no tactical readiness implied.",
    tags: ["public base", "air", "mediterranean"],
  },
  {
    id: "ctx-base-mihail-kogalniceanu",
    name: "Mihail Kogalniceanu",
    type: "military_base",
    category: "air base",
    region: "Black Sea",
    country: "Romania",
    coordinates: [44.36, 28.49],
    geoAccuracy: "city",
    importance: 78,
    whyItMatters: "Publicly known facility relevant to Black Sea and NATO eastern flank context.",
    riskNotes: "Public contextual reference only; no tactical readiness implied.",
    tags: ["public base", "black sea", "nato"],
  },
  {
    id: "ctx-base-lakenheath-mildenhall",
    name: "Lakenheath / Mildenhall",
    type: "military_base",
    category: "air base area",
    region: "United Kingdom",
    country: "United Kingdom",
    coordinates: [52.36, 0.49],
    geoAccuracy: "region",
    importance: 74,
    whyItMatters: "Publicly known air facility area relevant to NATO and European theater context.",
    riskNotes: "Public contextual reference only; no tactical readiness implied.",
    tags: ["public base", "air", "nato"],
  },
];

export function normalizeContextLayerItem(item) {
  if (!item || !Array.isArray(item.coordinates)) return null;
  const [lat, lng] = item.coordinates;
  if (!Number.isFinite(lat) || !Number.isFinite(lng)) return null;
  return {
    ...item,
    title: item.name,
    category: item.category ?? item.type,
    country: item.country ?? item.region ?? "Unspecified",
    importance: Number.isFinite(item.importance) ? item.importance : 50,
    source: item.source ?? "Curated public reference",
    sourceUrl: item.sourceUrl ?? null,
    lastUpdated: item.lastUpdated ?? "2026-05-31",
    lat,
    lng,
    tags: Array.isArray(item.tags) ? item.tags : [],
  };
}

export function getLayerDensityCap(layerKey, density = "low") {
  return LAYER_DENSITY_CAPS[layerKey]?.[density] ?? LAYER_DENSITY_CAPS[layerKey]?.low ?? 100;
}

export function getContextItemsForLayer(layerKey) {
  const def = CONTEXT_LAYER_DEFS[layerKey];
  if (!def) return [];
  return CONTEXT_LAYER_ITEMS
    .filter((item) => item.type === def.type)
    .map(normalizeContextLayerItem)
    .filter(Boolean)
    .sort((a, b) => Number(b.importance ?? 0) - Number(a.importance ?? 0));
}
