export const CONTEXT_LAYER_STORAGE_KEY = "grigori:context-layers";

export const CONTEXT_LAYER_DEFS = {
  contextChokepoints: {
    label: "Chokepoints",
    type: "chokepoint",
    icon: "C",
    color: "#f7b84b",
    desc: "Strategic maritime chokepoints",
  },
  contextPorts: {
    label: "Ports",
    type: "port",
    icon: "P",
    color: "#69e7ff",
    desc: "Major port and logistics nodes",
  },
  contextAirports: {
    label: "Airports",
    type: "airport",
    icon: "A",
    color: "#9bd6ff",
    desc: "Strategic aviation nodes",
  },
  contextEnergy: {
    label: "Energy",
    type: "energy",
    icon: "E",
    color: "#6ee7b7",
    desc: "Energy infrastructure context",
  },
};

export const CONTEXT_LAYER_ITEMS = [
  {
    id: "ctx-hormuz",
    name: "Strait of Hormuz",
    type: "chokepoint",
    region: "Persian Gulf / Gulf of Oman",
    coordinates: [26.6, 56.3],
    geoAccuracy: "region",
    whyItMatters: "Critical oil and LNG transit chokepoint linking Gulf producers to global shipping routes.",
    tags: ["oil", "shipping", "iran", "gulf"],
  },
  {
    id: "ctx-bab-el-mandeb",
    name: "Bab el-Mandeb",
    type: "chokepoint",
    region: "Red Sea / Gulf of Aden",
    coordinates: [12.6, 43.3],
    geoAccuracy: "region",
    whyItMatters: "Narrow maritime passage connecting the Red Sea to the Gulf of Aden and Suez-bound traffic.",
    tags: ["shipping", "red sea", "suez", "yemen"],
  },
  {
    id: "ctx-suez",
    name: "Suez Canal",
    type: "chokepoint",
    region: "Egypt",
    coordinates: [30.6, 32.3],
    geoAccuracy: "region",
    whyItMatters: "Major Europe-Asia shipping corridor; disruption can reroute vessels around the Cape of Good Hope.",
    tags: ["shipping", "trade", "egypt"],
  },
  {
    id: "ctx-bosporus",
    name: "Bosporus",
    type: "chokepoint",
    region: "Turkey / Black Sea",
    coordinates: [41.12, 29.06],
    geoAccuracy: "region",
    whyItMatters: "Gateway between the Black Sea and Mediterranean for naval, grain, and energy-linked traffic.",
    tags: ["black sea", "shipping", "turkey"],
  },
  {
    id: "ctx-taiwan-strait",
    name: "Taiwan Strait",
    type: "chokepoint",
    region: "Taiwan / China",
    coordinates: [24.5, 120.8],
    geoAccuracy: "region",
    whyItMatters: "Strategic maritime and air corridor near critical semiconductor supply chains.",
    tags: ["taiwan", "semiconductors", "shipping"],
  },
  {
    id: "ctx-malacca",
    name: "Strait of Malacca",
    type: "chokepoint",
    region: "Malaysia / Singapore / Indonesia",
    coordinates: [2.6, 101.0],
    geoAccuracy: "region",
    whyItMatters: "One of the world's busiest energy and container shipping corridors.",
    tags: ["shipping", "energy", "asia"],
  },
  {
    id: "ctx-panama",
    name: "Panama Canal",
    type: "chokepoint",
    region: "Panama",
    coordinates: [9.08, -79.68],
    geoAccuracy: "region",
    whyItMatters: "Key Atlantic-Pacific transit corridor sensitive to drought, congestion, and trade disruption.",
    tags: ["shipping", "trade"],
  },
  {
    id: "ctx-gibraltar",
    name: "Strait of Gibraltar",
    type: "chokepoint",
    region: "Western Mediterranean",
    coordinates: [35.98, -5.6],
    geoAccuracy: "region",
    whyItMatters: "Mediterranean access point for Atlantic shipping, naval movement, and energy routes.",
    tags: ["shipping", "mediterranean"],
  },
  {
    id: "ctx-port-rotterdam",
    name: "Port of Rotterdam",
    type: "port",
    region: "Netherlands",
    coordinates: [51.95, 4.14],
    geoAccuracy: "city",
    whyItMatters: "Major European energy, container, and industrial logistics hub.",
    tags: ["port", "europe", "energy"],
  },
  {
    id: "ctx-port-singapore",
    name: "Port of Singapore",
    type: "port",
    region: "Singapore",
    coordinates: [1.26, 103.82],
    geoAccuracy: "city",
    whyItMatters: "Critical transshipment and bunkering hub near the Malacca-South China Sea corridor.",
    tags: ["port", "shipping", "asia"],
  },
  {
    id: "ctx-port-fujairah",
    name: "Fujairah",
    type: "port",
    region: "United Arab Emirates",
    coordinates: [25.12, 56.36],
    geoAccuracy: "city",
    whyItMatters: "Strategic oil storage and bunkering node outside the Strait of Hormuz.",
    tags: ["port", "oil", "hormuz"],
  },
  {
    id: "ctx-port-constanta",
    name: "Constanta",
    type: "port",
    region: "Romania / Black Sea",
    coordinates: [44.16, 28.65],
    geoAccuracy: "city",
    whyItMatters: "Black Sea port relevant to grain, NATO logistics, and regional shipping disruption.",
    tags: ["port", "black sea", "grain"],
  },
  {
    id: "ctx-airport-dxb",
    name: "Dubai International",
    type: "airport",
    region: "United Arab Emirates",
    coordinates: [25.25, 55.36],
    geoAccuracy: "city",
    whyItMatters: "Major global aviation hub near Gulf escalation and energy chokepoint risks.",
    tags: ["airport", "gulf", "logistics"],
  },
  {
    id: "ctx-airport-istanbul",
    name: "Istanbul Airport",
    type: "airport",
    region: "Turkey",
    coordinates: [41.26, 28.74],
    geoAccuracy: "city",
    whyItMatters: "Major aviation hub near Bosporus and Black Sea-related transit corridors.",
    tags: ["airport", "black sea", "turkey"],
  },
  {
    id: "ctx-airport-ben-gurion",
    name: "Ben Gurion Airport",
    type: "airport",
    region: "Israel",
    coordinates: [32.0, 34.89],
    geoAccuracy: "city",
    whyItMatters: "Regional aviation node sensitive to Middle East escalation and airspace disruption.",
    tags: ["airport", "middle east"],
  },
  {
    id: "ctx-energy-kharg",
    name: "Kharg Island",
    type: "energy",
    region: "Iran / Persian Gulf",
    coordinates: [29.24, 50.31],
    geoAccuracy: "region",
    whyItMatters: "Iranian oil export node relevant to Gulf and Hormuz risk monitoring.",
    tags: ["oil", "iran", "hormuz"],
  },
  {
    id: "ctx-energy-abqaiq",
    name: "Abqaiq",
    type: "energy",
    region: "Saudi Arabia",
    coordinates: [25.94, 49.67],
    geoAccuracy: "city",
    whyItMatters: "Major Saudi oil processing infrastructure with strategic energy-market relevance.",
    tags: ["oil", "saudi", "energy"],
  },
  {
    id: "ctx-energy-ras-tanura",
    name: "Ras Tanura",
    type: "energy",
    region: "Saudi Arabia / Persian Gulf",
    coordinates: [26.65, 50.16],
    geoAccuracy: "region",
    whyItMatters: "Major oil terminal and refinery area near Gulf maritime security dynamics.",
    tags: ["oil", "terminal", "gulf"],
  },
  {
    id: "ctx-energy-sumed",
    name: "Suez / SUMED Energy Corridor",
    type: "energy",
    region: "Egypt",
    coordinates: [29.95, 32.55],
    geoAccuracy: "region",
    whyItMatters: "Energy transit context connecting Red Sea, Suez, and Mediterranean flows.",
    tags: ["oil", "suez", "pipeline"],
  },
];

export function normalizeContextLayerItem(item) {
  if (!item || !Array.isArray(item.coordinates)) return null;
  const [lat, lng] = item.coordinates;
  if (!Number.isFinite(lat) || !Number.isFinite(lng)) return null;
  return {
    ...item,
    title: item.name,
    lat,
    lng,
    tags: Array.isArray(item.tags) ? item.tags : [],
  };
}

export function getContextItemsForLayer(layerKey) {
  const def = CONTEXT_LAYER_DEFS[layerKey];
  if (!def) return [];
  return CONTEXT_LAYER_ITEMS
    .filter((item) => item.type === def.type)
    .map(normalizeContextLayerItem)
    .filter(Boolean);
}
